name: thepassage
adopt-info: passage-source
base: core22
architectures:
- amd64
confinement: strict
grade: stable
issues: https://github.com/kenvandine/thepassage-snap/issues
contact: https://github.com/kenvandine/thepassage-snap/issues

apps:
  thepassage:
    desktop: com.endlessnetwork.passage.desktop
    extensions: [gnome]
    command: The.Passage/The.Passage.x86_64
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  thepassage:
    source: https://github.com/endless-network/ThePassage_Binary/releases/download/v2.0/The.Passage.zip
    plugin: dump
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/The.Passage
      mv $CRAFT_PRIME/'The Passage'/'The Passage.x86_64' $CRAFT_PRIME/The.Passage/The.Passage.x86_64
      mv $CRAFT_PRIME/'The Passage'/'The Passage_Data' $CRAFT_PRIME/The.Passage/'The.Passage_Data'
      rm -r $CRAFT_PRIME/'The Passage'
      chmod +x $CRAFT_PRIME/The.Passage/The.Passage.x86_64
  passage-source:
    source: https://github.com/endless-network/ThePassage_Binary/archive/refs/tags/v2.0.tar.gz
    plugin: dump
    parse-info: [com.endlessnetwork.passage.appdata.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=com.endlessnetwork.passage$|Icon=${SNAP}/meta/gui/icon.png|g' $CRAFT_PART_SRC/com.endlessnetwork.passage.desktop
      sed -i 's|Exec=com.endlessnetwork.passage.sh$|Exec=passage|g' $CRAFT_PART_SRC/com.endlessnetwork.passage.desktop
      # Work around the latest version number missing from the releases section of appdata
      sed -i 's|version="1.34|version="2.0|g' $CRAFT_PART_SRC/com.endlessnetwork.passage.appdata.xml
      
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp com.endlessm.passage_128.png $CRAFT_PART_INSTALL/meta/gui/icon.png
